-- CreateEnum
CREATE TYPE "public"."AdminRole" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'MODERATOR', 'SUPPORT', 'ANALYST');

-- CreateEnum
CREATE TYPE "public"."UserReportType" AS ENUM ('HARASSMENT', 'SPAM', 'FRAUD', 'INAPPROPRIATE_CONTENT', 'FAKE_PROFILE', 'SCAM', 'PAYMENT_DISPUTE', 'TERMS_VIOLATION', 'OTHER');

-- CreateEnum
CREATE TYPE "public"."ContentReportType" AS ENUM ('LISTING', 'MESSAGE', 'REVIEW', 'PROFILE', 'IMAGE', 'OFFER');

-- CreateEnum
CREATE TYPE "public"."ContentReportReason" AS ENUM ('INAPPROPRIATE_CONTENT', 'SPAM', 'FRAUD', 'MISLEADING_INFORMATION', 'PROHIBITED_ITEMS', 'COPYRIGHT_VIOLATION', 'HATE_SPEECH', 'VIOLENCE', 'ADULT_CONTENT', 'FAKE_LISTING', 'PRICE_MANIPULATION', 'OTHER');

-- CreateEnum
CREATE TYPE "public"."ReportStatus" AS ENUM ('PENDING', 'UNDER_REVIEW', 'INVESTIGATING', 'RESOLVED', 'DISMISSED', 'ESCALATED', 'CLOSED');

-- CreateEnum
CREATE TYPE "public"."ReportPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT', 'CRITICAL');

-- CreateEnum
CREATE TYPE "public"."ModerationAction" AS ENUM ('NO_ACTION', 'WARNING_SENT', 'CONTENT_REMOVED', 'CONTENT_EDITED', 'USER_SUSPENDED', 'USER_BANNED', 'LISTING_HIDDEN', 'LISTING_REMOVED', 'OFFER_CANCELLED', 'ACCOUNT_RESTRICTED', 'ESCALATE_TO_ADMIN', 'REQUIRE_VERIFICATION');

-- CreateEnum
CREATE TYPE "public"."ModerationTriggerType" AS ENUM ('KEYWORD_MATCH', 'IMAGE_ANALYSIS', 'USER_REPORTS', 'BEHAVIOR_PATTERN', 'PRICE_ANOMALY', 'FREQUENCY_LIMIT', 'AI_DETECTION', 'MANUAL_REVIEW');

-- CreateEnum
CREATE TYPE "public"."AuditSeverity" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

-- CreateEnum
CREATE TYPE "public"."AnalyticsPeriod" AS ENUM ('HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY');

-- CreateEnum
CREATE TYPE "public"."ServiceStatus" AS ENUM ('HEALTHY', 'DEGRADED', 'UNHEALTHY', 'MAINTENANCE', 'UNKNOWN');

-- CreateTable
CREATE TABLE "public"."AdminUser" (
    "id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" "public"."AdminRole" NOT NULL,
    "name" TEXT NOT NULL,
    "firstName" TEXT,
    "lastName" TEXT,
    "phoneNumber" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isBlocked" BOOLEAN NOT NULL DEFAULT false,
    "lastLoginAt" TIMESTAMP(3),
    "lastLoginIp" TEXT,
    "loginAttempts" INTEGER NOT NULL DEFAULT 0,
    "lockedUntil" TIMESTAMP(3),
    "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false,
    "twoFactorSecret" TEXT,
    "twoFactorBackupCodes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "ipWhitelist" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "sessionToken" TEXT,
    "sessionExpiresAt" TIMESTAMP(3),
    "passwordChangedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdById" UUID,

    CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AdminAuditLog" (
    "id" UUID NOT NULL,
    "action" "public"."AdminAction" NOT NULL,
    "targetType" "public"."AuditTargetType" NOT NULL,
    "targetId" UUID,
    "description" TEXT NOT NULL,
    "details" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "previousData" JSONB,
    "newData" JSONB,
    "reason" TEXT,
    "notes" TEXT,
    "severity" "public"."AuditSeverity" NOT NULL DEFAULT 'MEDIUM',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "adminId" UUID NOT NULL,

    CONSTRAINT "AdminAuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."UserReport" (
    "id" UUID NOT NULL,
    "reportType" "public"."UserReportType" NOT NULL,
    "reason" TEXT NOT NULL,
    "details" TEXT,
    "evidence" JSONB,
    "status" "public"."ReportStatus" NOT NULL DEFAULT 'PENDING',
    "priority" "public"."ReportPriority" NOT NULL DEFAULT 'MEDIUM',
    "resolution" TEXT,
    "resolutionDetails" JSONB,
    "resolvedAt" TIMESTAMP(3),
    "escalatedAt" TIMESTAMP(3),
    "escalationReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "reporterId" UUID NOT NULL,
    "reportedUserId" UUID NOT NULL,
    "resolvedById" UUID,

    CONSTRAINT "UserReport_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ContentReport" (
    "id" UUID NOT NULL,
    "contentType" "public"."ContentReportType" NOT NULL,
    "contentId" UUID NOT NULL,
    "reportType" "public"."ContentReportReason" NOT NULL,
    "reason" TEXT NOT NULL,
    "details" TEXT,
    "evidence" JSONB,
    "status" "public"."ReportStatus" NOT NULL DEFAULT 'PENDING',
    "priority" "public"."ReportPriority" NOT NULL DEFAULT 'MEDIUM',
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "detectionMethod" TEXT,
    "confidenceScore" DOUBLE PRECISION,
    "resolution" TEXT,
    "resolutionAction" "public"."ModerationAction",
    "resolutionDetails" JSONB,
    "resolvedAt" TIMESTAMP(3),
    "escalatedAt" TIMESTAMP(3),
    "escalationReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "reporterId" UUID,
    "resolvedById" UUID,

    CONSTRAINT "ContentReport_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ModerationRule" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "priority" INTEGER NOT NULL DEFAULT 1,
    "triggerType" "public"."ModerationTriggerType" NOT NULL,
    "triggerConfig" JSONB NOT NULL,
    "actionType" "public"."ModerationAction" NOT NULL,
    "actionConfig" JSONB,
    "threshold" DOUBLE PRECISION,
    "frequency" INTEGER,
    "appliesToRegions" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "appliesToCategories" "public"."ListingCategory"[] DEFAULT ARRAY[]::"public"."ListingCategory"[],
    "triggerCount" INTEGER NOT NULL DEFAULT 0,
    "actionCount" INTEGER NOT NULL DEFAULT 0,
    "lastTriggeredAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdById" UUID NOT NULL,

    CONSTRAINT "ModerationRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."PlatformAnalytics" (
    "id" UUID NOT NULL,
    "date" DATE NOT NULL,
    "period" "public"."AnalyticsPeriod" NOT NULL DEFAULT 'DAILY',
    "totalUsers" INTEGER NOT NULL DEFAULT 0,
    "activeUsers" INTEGER NOT NULL DEFAULT 0,
    "newUsers" INTEGER NOT NULL DEFAULT 0,
    "verifiedUsers" INTEGER NOT NULL DEFAULT 0,
    "blockedUsers" INTEGER NOT NULL DEFAULT 0,
    "totalListings" INTEGER NOT NULL DEFAULT 0,
    "activeListings" INTEGER NOT NULL DEFAULT 0,
    "newListings" INTEGER NOT NULL DEFAULT 0,
    "approvedListings" INTEGER NOT NULL DEFAULT 0,
    "rejectedListings" INTEGER NOT NULL DEFAULT 0,
    "totalOffers" INTEGER NOT NULL DEFAULT 0,
    "acceptedOffers" INTEGER NOT NULL DEFAULT 0,
    "completedTrades" INTEGER NOT NULL DEFAULT 0,
    "tradeVolumeInKobo" BIGINT NOT NULL DEFAULT 0,
    "averageTradeValue" INTEGER NOT NULL DEFAULT 0,
    "revenueInKobo" BIGINT NOT NULL DEFAULT 0,
    "feesCollectedInKobo" BIGINT NOT NULL DEFAULT 0,
    "escrowVolumeInKobo" BIGINT NOT NULL DEFAULT 0,
    "regionalData" JSONB NOT NULL,
    "totalReports" INTEGER NOT NULL DEFAULT 0,
    "resolvedReports" INTEGER NOT NULL DEFAULT 0,
    "pendingReports" INTEGER NOT NULL DEFAULT 0,
    "moderationActions" INTEGER NOT NULL DEFAULT 0,
    "apiRequestCount" INTEGER NOT NULL DEFAULT 0,
    "errorCount" INTEGER NOT NULL DEFAULT 0,
    "averageResponseTime" INTEGER NOT NULL DEFAULT 0,
    "uptime" DOUBLE PRECISION NOT NULL DEFAULT 100.0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PlatformAnalytics_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."SystemHealth" (
    "id" UUID NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "apiStatus" "public"."ServiceStatus" NOT NULL DEFAULT 'HEALTHY',
    "databaseStatus" "public"."ServiceStatus" NOT NULL DEFAULT 'HEALTHY',
    "redisStatus" "public"."ServiceStatus" NOT NULL DEFAULT 'HEALTHY',
    "storageStatus" "public"."ServiceStatus" NOT NULL DEFAULT 'HEALTHY',
    "paymentStatus" "public"."ServiceStatus" NOT NULL DEFAULT 'HEALTHY',
    "cpuUsage" DOUBLE PRECISION NOT NULL,
    "memoryUsage" DOUBLE PRECISION NOT NULL,
    "diskUsage" DOUBLE PRECISION NOT NULL,
    "dbConnections" INTEGER NOT NULL,
    "dbSlowQueries" INTEGER NOT NULL,
    "dbErrors" INTEGER NOT NULL,
    "requestsPerMinute" INTEGER NOT NULL,
    "averageResponseTime" INTEGER NOT NULL,
    "errorRate" DOUBLE PRECISION NOT NULL,
    "queueSize" INTEGER NOT NULL,
    "failedJobs" INTEGER NOT NULL,
    "processingTime" INTEGER NOT NULL,
    "alerts" JSONB,
    "alertCount" INTEGER NOT NULL DEFAULT 0,
    "criticalAlerts" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "SystemHealth_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AdminUser_email_key" ON "public"."AdminUser"("email");

-- CreateIndex
CREATE INDEX "AdminUser_email_idx" ON "public"."AdminUser"("email");

-- CreateIndex
CREATE INDEX "AdminUser_role_idx" ON "public"."AdminUser"("role");

-- CreateIndex
CREATE INDEX "AdminUser_isActive_isBlocked_idx" ON "public"."AdminUser"("isActive", "isBlocked");

-- CreateIndex
CREATE INDEX "AdminUser_lastLoginAt_idx" ON "public"."AdminUser"("lastLoginAt");

-- CreateIndex
CREATE INDEX "AdminUser_createdById_idx" ON "public"."AdminUser"("createdById");

-- CreateIndex
CREATE INDEX "AdminAuditLog_adminId_idx" ON "public"."AdminAuditLog"("adminId");

-- CreateIndex
CREATE INDEX "AdminAuditLog_targetType_targetId_idx" ON "public"."AdminAuditLog"("targetType", "targetId");

-- CreateIndex
CREATE INDEX "AdminAuditLog_action_idx" ON "public"."AdminAuditLog"("action");

-- CreateIndex
CREATE INDEX "AdminAuditLog_severity_idx" ON "public"."AdminAuditLog"("severity");

-- CreateIndex
CREATE INDEX "AdminAuditLog_createdAt_idx" ON "public"."AdminAuditLog"("createdAt");

-- CreateIndex
CREATE INDEX "UserReport_reporterId_idx" ON "public"."UserReport"("reporterId");

-- CreateIndex
CREATE INDEX "UserReport_reportedUserId_idx" ON "public"."UserReport"("reportedUserId");

-- CreateIndex
CREATE INDEX "UserReport_status_idx" ON "public"."UserReport"("status");

-- CreateIndex
CREATE INDEX "UserReport_priority_idx" ON "public"."UserReport"("priority");

-- CreateIndex
CREATE INDEX "UserReport_reportType_idx" ON "public"."UserReport"("reportType");

-- CreateIndex
CREATE INDEX "UserReport_createdAt_idx" ON "public"."UserReport"("createdAt");

-- CreateIndex
CREATE INDEX "UserReport_resolvedById_idx" ON "public"."UserReport"("resolvedById");

-- CreateIndex
CREATE INDEX "ContentReport_contentType_contentId_idx" ON "public"."ContentReport"("contentType", "contentId");

-- CreateIndex
CREATE INDEX "ContentReport_reporterId_idx" ON "public"."ContentReport"("reporterId");

-- CreateIndex
CREATE INDEX "ContentReport_status_idx" ON "public"."ContentReport"("status");

-- CreateIndex
CREATE INDEX "ContentReport_priority_idx" ON "public"."ContentReport"("priority");

-- CreateIndex
CREATE INDEX "ContentReport_reportType_idx" ON "public"."ContentReport"("reportType");

-- CreateIndex
CREATE INDEX "ContentReport_isAutoGenerated_idx" ON "public"."ContentReport"("isAutoGenerated");

-- CreateIndex
CREATE INDEX "ContentReport_createdAt_idx" ON "public"."ContentReport"("createdAt");

-- CreateIndex
CREATE INDEX "ContentReport_resolvedById_idx" ON "public"."ContentReport"("resolvedById");

-- CreateIndex
CREATE INDEX "ModerationRule_isActive_idx" ON "public"."ModerationRule"("isActive");

-- CreateIndex
CREATE INDEX "ModerationRule_triggerType_idx" ON "public"."ModerationRule"("triggerType");

-- CreateIndex
CREATE INDEX "ModerationRule_priority_idx" ON "public"."ModerationRule"("priority");

-- CreateIndex
CREATE INDEX "ModerationRule_createdById_idx" ON "public"."ModerationRule"("createdById");

-- CreateIndex
CREATE INDEX "PlatformAnalytics_date_idx" ON "public"."PlatformAnalytics"("date");

-- CreateIndex
CREATE INDEX "PlatformAnalytics_period_idx" ON "public"."PlatformAnalytics"("period");

-- CreateIndex
CREATE UNIQUE INDEX "PlatformAnalytics_date_period_key" ON "public"."PlatformAnalytics"("date", "period");

-- CreateIndex
CREATE INDEX "SystemHealth_timestamp_idx" ON "public"."SystemHealth"("timestamp");

-- CreateIndex
CREATE INDEX "SystemHealth_apiStatus_idx" ON "public"."SystemHealth"("apiStatus");

-- CreateIndex
CREATE INDEX "SystemHealth_alertCount_idx" ON "public"."SystemHealth"("alertCount");

-- AddForeignKey
ALTER TABLE "public"."AdminUser" ADD CONSTRAINT "AdminUser_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "public"."AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AdminAuditLog" ADD CONSTRAINT "AdminAuditLog_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "public"."AdminUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."UserReport" ADD CONSTRAINT "UserReport_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "public"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."UserReport" ADD CONSTRAINT "UserReport_reportedUserId_fkey" FOREIGN KEY ("reportedUserId") REFERENCES "public"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."UserReport" ADD CONSTRAINT "UserReport_resolvedById_fkey" FOREIGN KEY ("resolvedById") REFERENCES "public"."AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ContentReport" ADD CONSTRAINT "ContentReport_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ContentReport" ADD CONSTRAINT "ContentReport_resolvedById_fkey" FOREIGN KEY ("resolvedById") REFERENCES "public"."AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ModerationRule" ADD CONSTRAINT "ModerationRule_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "public"."AdminUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
